### PR TITLE
UUID as ID key for entities

### LINKED ISSUE #69: feature: Support schema with UUID type id field
### ✨ Describe the feature you'd like

When specifying an **id** field of type UUID, it is unable to generate the oapi.

## Cause
```
func (Pet) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Default(uuid.New).Unique(),
		field.String("name").
			Annotations(
				entrest.WithExample("Kuro"),
				entrest.WithSortable(true),
				entrest.WithFilter(entrest.FilterGroupEqual|entrest.FilterGroupArray),
			),
...
```

## Error
```
panic: failed to generate schema for field ID: no openapi type exists for type "[16]byte" of field ID
```

### 🌧 Is your feature request related to a problem?

_No response_

### 🔎 Describe alternatives you've considered

NA

### ⚠ If implemented, do you think this feature will be a breaking change to users?

No

### ⚙ Additional context

_No response_

### 🤝 Requirements

- [X] I have confirmed that someone else has not [submitted a similar feature request](../labels/enhancement).
- [X] If implemented, I believe this feature will help others, in addition to solving my problems.
- [X] I have looked into alternative solutions to the best of my ability.
- [X] (optional) I would be willing to contribute to testing this feature if implemented, or making a PR to implement this functionality.

### PR DESCRIPTION
**Pull request by akeelnazir**
## 🚀 Changes proposed by this PR

The extension does not work for schema files that use uuid.UUID for ID fields. This fix checks for the flag `AllowClientUUIDs` and takes necessary action.

### 🔗 Related bug reports/feature requests

- fixes #69 

### 🧰 Type of change

- [ X] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected).
- [ ] This change requires (or is) a documentation update.

### 🤝 Requirements

- [x] ✍ I have read and agree to this projects [Code of Conduct](../../blob/master/.github/CODE_OF_CONDUCT.md).
- [x] ✍ I have read and agree to this projects [Contribution Guidelines](../../blob/master/.github/CONTRIBUTING.md).
- [x] ✍ I have read and agree to the [Developer Certificate of Origin](https://developercertificate.org/).
- [x] 🔎 I have performed a self-review of my own changes.
- [x] 🎨 My changes follow the style guidelines of this project.

- [x] 💬 My changes as properly commented, primarily for hard-to-understand areas.
- [x] 📝 I have made corresponding changes to the documentation.
- [x] 🧪 I have included tests (if necessary) for this change.

### CODE REVIEW

**Review by lrstanley — CHANGES_REQUESTED** [review]
Couple of things:
- UUIDs should be supported in a more general sense, not using `uuid.UUID` specifically. People use different libraries, and we should use the graph information to auto-determine the type.
- There are various other locations where `int` and `number` is explicitly used, which will also need to be updated (e.g. inside of the spec).
- We shouldn't directly call `uuid.Parse` in the handler -- theoretically, any supported UUID should have a JSON or string marshaller interface.
- `AllowClientUUIDs` isn't meant for toggling UUID support, it's actually to allow clients to provide their own UUID during CREATE operations. Ideally, UUID support should be automatic. `AllowClientUUIDs` was just a carry-over from entoas, and looks like I didn't cover all of the other necessary UUID support through.
- We'll also need some tests to cover many of the same scenarios where an integer based ID is used today.
  - Both config_test.go based tests, as well as ones under `kitchensink` (integration tests).

If you're not able to get to these items as part of the PR, I should be able to tackle it soon, however, I am currently moving to another state, so the next two weeks I may not be able to get to it.

**Comment by jordanfowler** [comment]
Given there is a concrete definition for what the a UUID actually is defined by RFC 4122, it seems like ogen or this extension should know how to marshal `[16]byte` regardless of which library is being used to actually generate UUIDs. For reference:

```
// A UUID is a 128 bit (16 byte) Universal Unique IDentifier as defined in RFC
// 4122.
type UUID [16]byte
```

**Comment by lrstanley** [comment]
@jordanfowler while there may be an RFC for UUIDs, to my knowledge, Ent does not impose those restrictions, so we should not. I'm confident some Ent users use "uuid" fields in which are not using an RFC-compliant solution.

**Comment by lrstanley** [comment]
Sorry, I'm super late on getting to the implementation of this, but take a look at https://github.com/lrstanley/entrest/pull/81 and let me know your thoughts. Plan on merging sometime tomorrow.

Wanted to make sure the approach used overlaps as much as possible with how Ent marshals/unmarshals UUID (or custom) ID fields. It's not _exactly_ the same, but it's very close (since Ent doesn't expose reusable logic for it).

I've tested with a few different UUID implementations (and other ID types, like string), and seems to work well. Feel free to test yourself and let me know if you have any concerns with my approach.

**Pull request closed without merging**
